"""set nullable to project owner

Revision ID: 14478c5828fa
Revises: 2e9990d58e22
Create Date: 2026-09-01 22:03:36.189648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14478c5828fa'
down_revision: Union[str, Sequence[str], None] = '2e9990d58e22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects') as batch_op:
        batch_op.alter_column(
            'owner_id',
            existing_type=sa.Integer(),
            nullable=True
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects') as batch_op:
        batch_op.alter_column(
            'owner_id',
            existing_type=sa.Integer(),
            nullable=False
        )
    # ### end Alembic commands ###
