"""add cascade in project owner

Revision ID: bbbf034a8d9e
Revises: f6bbdc3ee028
Create Date: 2026-09-01 22:49:09.473524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbbf034a8d9e'
down_revision: Union[str, Sequence[str], None] = 'f6bbdc3ee028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'projects_new',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(200), nullable=False),
        sa.Column('owner_id', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(
            ['owner_id'],
            ['users.id'],
            ondelete='CASCADE',
            name='fk_projects_owner_id'
        )
    )

    op.execute('''
        INSERT INTO projects_new (id, name, owner_id)
        SELECT id, name, owner_id FROM projects
    ''')

    op.drop_table('projects')

    op.rename_table('projects_new', 'projects')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'projects_new',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(200), nullable=False),
        sa.Column('owner_id', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(
            ['owner_id'],
            ['users.id'],
            name='fk_projects_owner_id'
        )
    )

    op.execute('''
        INSERT INTO projects_new (id, name, owner_id)
        SELECT id, name, owner_id FROM projects
    ''')

    op.drop_table('projects')

    op.rename_table('projects_new', 'projects')
    # ### end Alembic commands ###
