"""add cascade in user project

Revision ID: f6bbdc3ee028
Revises: 14478c5828fa
Create Date: 2026-09-01 22:36:20.784029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6bbdc3ee028'
down_revision: Union[str, Sequence[str], None] = '14478c5828fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects') as batch_op:
        batch_op.alter_column(
            'owner_id',
            existing_type=sa.Integer(),
            nullable=False
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects') as batch_op:
        batch_op.alter_column(
            'owner_id',
            existing_type=sa.Integer(),
            nullable=True
        )
    # ### end Alembic commands ###
